-- Role-based security migration for an existing WD Management database.
-- Run once in Supabase SQL Editor after supabase-schema.sql / supabase-seed.sql.

alter table app_users add column if not exists employee_id bigint references employees(id) on delete set null;
alter table app_users add column if not exists must_change_password boolean not null default true;
alter table app_users add column if not exists password_set_at timestamptz;
alter table reports add column if not exists employee_id bigint references employees(id) on delete set null;
alter table weekly_reports add column if not exists employee_id bigint references employees(id) on delete set null;

create table if not exists task_email_notifications (
  id bigint generated by default as identity primary key,
  task_id bigint references tasks(id) on delete cascade,
  recipient_employee_id bigint references employees(id) on delete set null,
  recipient_name text not null,
  recipient_email text not null,
  subject text not null,
  message text not null,
  status text not null default 'Queued' check (status in ('Queued', 'Sent', 'Failed')),
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);
alter table task_email_notifications enable row level security;

create table if not exists password_events (
  id bigint generated by default as identity primary key,
  app_user_id text references app_users(id) on delete cascade,
  email text not null,
  event text not null check (event in ('temporary_created', 'temporary_reset', 'changed_by_user')),
  created_at timestamptz not null default now()
);
alter table password_events enable row level security;

alter table app_users drop constraint if exists app_users_role_check;
delete from app_users
where lower(email) in ('destamara.carissa@wdgroup.com', 'cantikaqiza@gmail.com')
  and id <> 'admin-general';
delete from app_users
where lower(email) = 'tegardarmawan59@gmail.com'
  and id <> 'head-general';
delete from app_users
where lower(email) = 'tegar@wdgroup.com'
  and id <> 'head-general';
delete from app_users
where lower(email) in ('dewi.wulandari@wdgroup.com', 'dewiiwulandari03@gmail.com')
  and id <> 'staff-general';
update app_users
set role = 'Wakil Owner',
    name = 'Destamara Carissa Feodora',
    email = 'cantikaqiza@gmail.com',
    division_id = 'all'
where role = 'Administrator' or lower(email) in ('admin@wdgroup.com', 'destamara.carissa@wdgroup.com', 'cantikaqiza@gmail.com') or id = 'admin-general';
update employees
set role = 'Wakil Owner',
    position = 'Wakil Owner',
    name = 'Destamara Carissa Feodora',
    email = 'cantikaqiza@gmail.com',
    division_id = 'all'
where role = 'Administrator' or lower(email) in ('admin@wdgroup.com', 'destamara.carissa@wdgroup.com', 'cantikaqiza@gmail.com') or id = 18;
alter table app_users add constraint app_users_role_check check (role in ('Owner', 'Kepala Divisi', 'Staff', 'Magang', 'Wakil Owner'));

create schema if not exists private;
revoke all on schema private from public;

update app_users
set email = 'dosenwildandeni@gmail.com',
    name = 'Wildan Deni Fahrezi',
    division_id = 'all',
    status = 'Aktif'
where id = 'owner-general' or role = 'Owner' or lower(email) = 'owner@wdgroup.com';

update employees
set email = 'dosenwildandeni@gmail.com',
    name = 'Wildan Deni Fahrezi',
    position = 'Owner',
    division_id = 'all',
    role = 'Owner',
    status = 'Aktif'
where id = 1 or role = 'Owner' or lower(email) = 'owner@wdgroup.com';

update app_users u
set employee_id = e.id
from employees e
where lower(u.email) = lower(e.email) and u.employee_id is null;

update app_users set employee_id = 1, division_id = 'all' where role = 'Owner' and employee_id is null;
update app_users set employee_id = 18, division_id = 'all' where role = 'Wakil Owner' and employee_id is null;
update app_users set employee_id = 2, name = 'Tegar', email = 'tegardarmawan59@gmail.com', division_id = 'it' where id = 'head-general';
update app_users set employee_id = 3, name = 'Yahya Muhammad', email = 'yahyaalbayaz@gmail.com', division_id = 'project-content' where id = 'head-content';
update app_users set employee_id = 4, name = 'Dewi Wulandari', email = 'dewiiwulandari03@gmail.com', division_id = 'project-content' where id = 'staff-general';

update employees
set name = 'Tegar',
    email = 'tegardarmawan59@gmail.com',
    role = 'Kepala Divisi',
    position = 'Tim Manajemen Sistem IT',
    division_id = 'it'
where id = 2 or lower(email) in ('tegar@wdgroup.com', 'tegardarmawan59@gmail.com');

update employees
set name = 'Yahya Muhammad',
    email = 'yahyaalbayaz@gmail.com',
    role = 'Kepala Divisi',
    position = 'Kepala Divisi Project Manager & Konten',
    division_id = 'project-content'
where id = 3 or lower(email) in ('yahya.muhammad@wdgroup.com', 'yahyaalbayaz@gmail.com');

update employees
set name = 'Dewi Wulandari',
    email = 'dewiiwulandari03@gmail.com',
    role = 'Staff',
    position = 'Tim Project Manager & Konten',
    division_id = 'project-content'
where id = 4 or lower(email) in ('dewi.wulandari@wdgroup.com', 'dewiiwulandari03@gmail.com', 'staff@wdgroup.com');

update employees
set role = 'Kepala Divisi',
    position = 'Kepala Divisi Administrasi & Booking',
    email = 'naylarizki16@gmail.com'
where id = 5 or lower(email) in ('nayla.rizki@wdgroup.com', 'naylarizki16@gmail.com');

update employees
set role = 'Kepala Divisi',
    position = 'Kepala Divisi Public Relation & Admin',
    email = 'alifadwi230506@gmail.com'
where id = 14 or lower(email) in ('alifa.kharisma@wdgroup.com', 'alifadwi230506@gmail.com');

insert into employees (name, email, position, division_id, role, status, joined_at)
select 'Teuku Arnel', 'teukujunefri@gmail.com', 'Tim Staff Media Production', 'media-production', 'Staff', 'Aktif', '2024-04-01'
where not exists (
  select 1 from employees where id = 16 or lower(email) in ('teuku.arnel@wdgroup.com', 'teukujunefri@gmail.com')
);

update employees
set name = 'Teuku Arnel',
    email = 'teukujunefri@gmail.com',
    position = 'Tim Staff Media Production',
    division_id = 'media-production',
    role = 'Staff',
    status = 'Aktif'
where id = 16 or lower(email) in ('teuku.arnel@wdgroup.com', 'teukujunefri@gmail.com');

update employees as e
set email = updates.email,
    name = updates.name,
    position = updates.position,
    division_id = updates.division_id,
    role = updates.role,
    status = 'Aktif'
from (values
  (3, 'Yahya Muhammad', 'yahyaalbayaz@gmail.com', 'Kepala Divisi Project Manager & Konten', 'project-content', 'Kepala Divisi'),
  (4, 'Dewi Wulandari', 'dewiiwulandari03@gmail.com', 'Tim Project Manager & Konten', 'project-content', 'Staff'),
  (5, 'Nayla Rizki Rachmania', 'naylarizki16@gmail.com', 'Kepala Divisi Administrasi & Booking', 'admin-booking', 'Kepala Divisi'),
  (6, 'Ayu Safitri', 'ayu808485@gmail.com', 'Tim Administrasi & Booking', 'admin-booking', 'Staff'),
  (7, 'M. Mirza Al-farizi', 'mijaa478@gmail.com', 'Tim Staff Media Production', 'media-production', 'Staff'),
  (8, 'Sandi Nabil Ristullah', 'sndeyszrwr@gmail.com', 'Staf Magang Media Production', 'media-production', 'Magang'),
  (9, 'Syahdan Alwinanta', 'syahdanalwin@gmail.com', 'Staf Magang Media Production', 'media-production', 'Magang'),
  (10, 'Rehan Rizkianto', 'ryypripayer@gmail.com', 'Staf Magang Media Production', 'media-production', 'Magang'),
  (11, 'Maulana Al Ayubi', 'maulanaalayubi59@gmail.com', 'Staf Magang Media Production', 'media-production', 'Magang'),
  (12, 'Irum Maqbullah', 'irummaqbullah@gmail.com', 'Staf Magang Media Production', 'media-production', 'Magang'),
  (13, 'Wahyu Agung Utomo', 'wahyupqxd@gmail.com', 'Staf Magang Media Production', 'media-production', 'Magang'),
  (14, 'Alifa Dwi Kharisma', 'alifadwi230506@gmail.com', 'Kepala Divisi Public Relation & Admin', 'public-relation-admin', 'Kepala Divisi'),
  (15, 'Febriyan Budi Prasetyo', 'febriyanbudi921@gmail.com', 'Tim Staff Public Relation & Admin', 'public-relation-admin', 'Staff'),
  (16, 'Teuku Arnel', 'teukujunefri@gmail.com', 'Tim Staff Media Production', 'media-production', 'Staff')
) as updates(id, name, email, position, division_id, role)
where e.id = updates.id;

delete from app_users
where employee_id in (8, 9, 10, 11, 12, 13)
  or lower(email) in (
    'sandi.nabil@wdgroup.com',
    'syahdan.alwinanta@wdgroup.com',
    'rehan.rizkianto@wdgroup.com',
    'maulana.ayubi@wdgroup.com',
    'khoirum.maqbullah@wdgroup.com',
    'wahyu.agung@wdgroup.com'
  );

update app_users as u
set email = updates.email,
    name = updates.name,
    division_id = updates.division_id,
    role = updates.role,
    status = 'Aktif',
    employee_id = updates.employee_id
from (values
  ('head-content', 3, 'Yahya Muhammad', 'yahyaalbayaz@gmail.com', 'project-content', 'Kepala Divisi'),
  ('staff-general', 4, 'Dewi Wulandari', 'dewiiwulandari03@gmail.com', 'project-content', 'Staff'),
  ('head-admin-booking', 5, 'Nayla Rizki Rachmania', 'naylarizki16@gmail.com', 'admin-booking', 'Kepala Divisi'),
  ('employee-6', 6, 'Ayu Safitri', 'ayu808485@gmail.com', 'admin-booking', 'Staff'),
  ('employee-7', 7, 'M. Mirza Al-farizi', 'mijaa478@gmail.com', 'media-production', 'Staff'),
  ('head-public-relation-admin', 14, 'Alifa Dwi Kharisma', 'alifadwi230506@gmail.com', 'public-relation-admin', 'Kepala Divisi'),
  ('employee-15', 15, 'Febriyan Budi Prasetyo', 'febriyanbudi921@gmail.com', 'public-relation-admin', 'Staff'),
  ('employee-16', 16, 'Teuku Arnel', 'teukujunefri@gmail.com', 'media-production', 'Staff')
) as updates(id, employee_id, name, email, division_id, role)
where u.id = updates.id or u.employee_id = updates.employee_id;

insert into app_users (id, name, email, role, division_id, status, employee_id) values
  ('head-content', 'Yahya Muhammad', 'yahyaalbayaz@gmail.com', 'Kepala Divisi', 'project-content', 'Aktif', 3),
  ('head-admin-booking', 'Nayla Rizki Rachmania', 'naylarizki16@gmail.com', 'Kepala Divisi', 'admin-booking', 'Aktif', 5),
  ('head-public-relation-admin', 'Alifa Dwi Kharisma', 'alifadwi230506@gmail.com', 'Kepala Divisi', 'public-relation-admin', 'Aktif', 14)
on conflict (email) do update set
  id = excluded.id,
  name = excluded.name,
  role = excluded.role,
  division_id = excluded.division_id,
  status = excluded.status,
  employee_id = excluded.employee_id;

insert into app_users (id, name, email, role, division_id, status, employee_id)
select
  'employee-' || e.id,
  e.name,
  e.email,
  e.role,
  e.division_id,
  e.status,
  e.id
from employees e
where e.email is not null and e.email <> ''
on conflict (email) do update set
  name = excluded.name,
  role = excluded.role,
  division_id = excluded.division_id,
  status = excluded.status,
  employee_id = excluded.employee_id;

update divisions d
set members = member_counts.total
from (
  select division_id, count(*)::integer as total
  from employees
  where status = 'Aktif'
    and division_id <> 'all'
  group by division_id
) member_counts
where d.id = member_counts.division_id;

update reports r set employee_id = e.id from employees e where lower(r.staff) = lower(e.name) and r.employee_id is null;
update weekly_reports r set employee_id = e.id from employees e where lower(r.staff) = lower(e.name) and r.employee_id is null;

update divisions d
set head = heads.name
from (
  select distinct on (division_id) division_id, name
  from employees
  where role = 'Kepala Divisi'
    and status = 'Aktif'
    and division_id <> 'all'
  order by division_id, id
) heads
where d.id = heads.division_id;

update divisions
set head = 'Belum ditentukan'
where (head is null or lower(head) in ('tegar', 'staff', 'staf'))
  and not exists (
     select 1
     from employees e
     where e.division_id = divisions.id
       and e.role = 'Kepala Divisi'
       and e.status = 'Aktif'
   );

create or replace function private.current_app_email()
returns text language sql stable security definer set search_path = public
as $$ select lower(coalesce(auth.jwt() ->> 'email', '')) $$;

create or replace function private.current_app_role()
returns text language sql stable security definer set search_path = public
as $$
  select role from app_users
  where lower(email) = private.current_app_email() and status = 'Aktif'
  limit 1
$$;

create or replace function private.current_app_division()
returns text language sql stable security definer set search_path = public
as $$
  select division_id from app_users
  where lower(email) = private.current_app_email() and status = 'Aktif'
  limit 1
$$;

create or replace function private.current_employee_id()
returns bigint language sql stable security definer set search_path = public
as $$
  select employee_id from app_users
  where lower(email) = private.current_app_email() and status = 'Aktif'
  limit 1
$$;

create or replace function private.is_management()
returns boolean language sql stable security definer set search_path = public
as $$ select coalesce(private.current_app_role() in ('Owner', 'Wakil Owner'), false) $$;

create or replace function private.can_access_division(target_division text)
returns boolean language sql stable security definer set search_path = public
as $$
  select coalesce(
    private.is_management()
    or target_division = 'all'
    or target_division = private.current_app_division(),
    false
  )
$$;

create or replace function public.mark_own_password_changed()
returns void language plpgsql security definer set search_path = public
as $$
begin
  update app_users
  set must_change_password = false,
      password_set_at = now()
  where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    and status = 'Aktif';

  insert into password_events (app_user_id, email, event)
  select id, email, 'changed_by_user'
  from app_users
  where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    and status = 'Aktif';
end;
$$;

do $$
declare policy_row record;
begin
  for policy_row in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'app_users', 'divisions', 'employees', 'tasks', 'task_email_notifications', 'task_submissions', 'password_events',
        'meetings', 'minutes', 'reports', 'weekly_reports', 'announcements',
        'documents', 'activity_logs', 'sops', 'app_settings'
      )
  loop
    execute format('drop policy if exists %I on %I.%I', policy_row.policyname, policy_row.schemaname, policy_row.tablename);
  end loop;
end $$;

create policy "role read app users" on app_users for select to authenticated
using (private.current_app_role() is not null);
create policy "management update app users" on app_users for update to authenticated
using (private.is_management()) with check (private.is_management());
create policy "scoped read password events" on password_events for select to authenticated
using (private.is_management() or lower(email) = private.current_app_email());

create policy "authenticated read divisions" on divisions for select to authenticated
using (private.current_app_role() is not null);
create policy "scoped read employees" on employees for select to authenticated
using (private.current_app_role() is not null);

create policy "scoped read tasks" on tasks for select to authenticated
using (private.current_app_role() is not null);
create policy "management insert tasks" on tasks for insert to authenticated
with check (
  private.is_management()
  or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division())
);
create policy "scoped update tasks" on tasks for update to authenticated
using (
  private.is_management()
  or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division())
)
with check (
  private.is_management()
  or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division())
);
create policy "management delete tasks" on tasks for delete to authenticated
using (private.is_management() or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division()));

create policy "scoped read task email notifications" on task_email_notifications for select to authenticated
using (
  private.is_management()
  or recipient_employee_id = private.current_employee_id()
  or lower(recipient_email) = private.current_app_email()
  or exists (
    select 1
    from tasks t
    where t.id = task_id
      and private.can_access_division(t.division_id)
  )
);
create policy "authenticated insert task email notifications" on task_email_notifications for insert to authenticated
with check (private.current_app_role() is not null);
create policy "management update task email notifications" on task_email_notifications for update to authenticated
using (private.is_management()) with check (private.is_management());

create policy "scoped read submissions" on task_submissions for select to authenticated
using (private.current_app_role() is not null);
create policy "staff insert submissions" on task_submissions for insert to authenticated
with check (
  private.current_app_role() in ('Owner', 'Wakil Owner', 'Kepala Divisi')
  and exists (select 1 from tasks t where t.id = task_id and t.assignee_id = private.current_employee_id())
);
create policy "scoped update submissions" on task_submissions for update to authenticated
using (
  private.is_management()
  or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division())
)
with check (
  private.is_management()
  or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division())
);

create policy "scoped read meetings" on meetings for select to authenticated using (private.current_app_role() is not null);
create policy "scoped insert meetings" on meetings for insert to authenticated
with check (private.is_management() or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division()));
create policy "scoped update meetings" on meetings for update to authenticated
using (private.is_management() or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division()))
with check (private.is_management() or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division()));
create policy "scoped delete meetings" on meetings for delete to authenticated
using (private.is_management() or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division()));

create policy "scoped read minutes" on minutes for select to authenticated using (private.current_app_role() is not null);
create policy "scoped insert minutes" on minutes for insert to authenticated
with check (private.is_management() or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division()));
create policy "scoped update minutes" on minutes for update to authenticated
using (private.is_management() or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division()))
with check (private.is_management() or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division()));
create policy "scoped delete minutes" on minutes for delete to authenticated
using (private.is_management() or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division()));

create policy "scoped read reports" on reports for select to authenticated
using (private.current_app_role() is not null);
create policy "staff insert reports" on reports for insert to authenticated
with check (private.current_app_role() in ('Owner', 'Wakil Owner', 'Kepala Divisi'));
create policy "scoped read weekly reports" on weekly_reports for select to authenticated
using (private.current_app_role() is not null);
create policy "staff insert weekly reports" on weekly_reports for insert to authenticated
with check (private.current_app_role() in ('Owner', 'Wakil Owner', 'Kepala Divisi'));

create policy "authenticated read announcements" on announcements for select to authenticated using (private.current_app_role() is not null);
create policy "management insert announcements" on announcements for insert to authenticated with check (private.is_management());
create policy "management update announcements" on announcements for update to authenticated using (private.is_management()) with check (private.is_management());
create policy "management delete announcements" on announcements for delete to authenticated using (private.is_management());

create policy "scoped read documents" on documents for select to authenticated using (private.current_app_role() is not null);
create policy "scoped insert documents" on documents for insert to authenticated
with check (
  private.is_management()
  or (private.current_app_role() = 'Kepala Divisi' and division_id = private.current_app_division())
);
create policy "management update documents" on documents for update to authenticated using (private.is_management()) with check (private.is_management());
create policy "management delete documents" on documents for delete to authenticated using (private.is_management());

create policy "management read activity logs" on activity_logs for select to authenticated using (private.current_app_role() is not null);
create policy "authenticated insert activity logs" on activity_logs for insert to authenticated with check (private.current_app_role() in ('Owner', 'Wakil Owner', 'Kepala Divisi'));
create policy "management update activity logs" on activity_logs for update to authenticated using (private.is_management()) with check (private.is_management());
create policy "management delete activity logs" on activity_logs for delete to authenticated using (private.is_management());

create policy "scoped read sops" on sops for select to authenticated using (private.current_app_role() is not null);
create policy "authenticated read settings" on app_settings for select to authenticated using (private.current_app_role() is not null);
create policy "owner insert settings" on app_settings for insert to authenticated with check (private.current_app_role() = 'Owner');
create policy "owner update settings" on app_settings for update to authenticated using (private.current_app_role() = 'Owner') with check (private.current_app_role() = 'Owner');

create or replace function private.enforce_staff_task_update()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if private.current_app_role() in ('Staff', 'Magang') then
    if old.assignee_id is distinct from private.current_employee_id()
      or new.assignee_id is distinct from old.assignee_id
      or new.division_id is distinct from old.division_id
      or new.title is distinct from old.title
      or new.description is distinct from old.description
      or new.deadline is distinct from old.deadline
      or new.assigned_by is distinct from old.assigned_by
      or new.assigned_by_name is distinct from old.assigned_by_name
      or new.progress > 95
      or coalesce(new.status, '') not in ('Belum Mulai', 'Proses', 'Terlambat', 'Menunggu Review', 'Revisi Dikirim Ulang')
      or coalesce(new.approval, '') not in ('Draft', 'Menunggu', 'Menunggu Review', 'Revisi')
    then
      raise exception 'Staf hanya dapat memperbarui progres dan pengumpulan tugas miliknya.';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_staff_task_update_trigger on tasks;
create trigger enforce_staff_task_update_trigger before update on tasks
for each row execute function private.enforce_staff_task_update();

create or replace function private.enforce_staff_submission_update()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if private.current_app_role() in ('Staff', 'Magang') then
    if coalesce(new.status, '') not in ('Menunggu Review', 'Revisi Dikirim Ulang', 'Terlambat')
      or new.reviewed_by is not null
      or new.reviewer_role is not null
      or new.reviewed_at is not null
    then
      raise exception 'Staf tidak dapat menentukan hasil review.';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_staff_submission_update_trigger on task_submissions;
create trigger enforce_staff_submission_update_trigger before insert or update on task_submissions
for each row execute function private.enforce_staff_submission_update();

update storage.buckets set public = false where id in ('task-submissions', 'company-documents');
drop policy if exists "authenticated upload task submissions" on storage.objects;
drop policy if exists "public read task submissions" on storage.objects;
drop policy if exists "authenticated upload company documents" on storage.objects;
drop policy if exists "public read company documents" on storage.objects;
drop policy if exists "authenticated read internal files" on storage.objects;
drop policy if exists "authenticated upload internal files" on storage.objects;
drop policy if exists "scoped read company documents" on storage.objects;
drop policy if exists "scoped upload company documents" on storage.objects;
drop policy if exists "authenticated read task files" on storage.objects;
drop policy if exists "staff upload task files" on storage.objects;
drop policy if exists "management delete company documents" on storage.objects;

create policy "scoped read company documents" on storage.objects for select to authenticated
using (
  bucket_id = 'company-documents'
  and private.current_app_role() is not null
);
create policy "scoped upload company documents" on storage.objects for insert to authenticated
with check (
  bucket_id = 'company-documents'
  and (
    private.is_management()
    or (
      private.current_app_role() = 'Kepala Divisi'
      and split_part(name, '/', 1) = private.current_app_division()
    )
  )
);
create policy "management delete company documents" on storage.objects for delete to authenticated
using (bucket_id = 'company-documents' and private.is_management());
create policy "authenticated read task files" on storage.objects for select to authenticated
using (bucket_id = 'task-submissions' and private.current_app_role() is not null);
create policy "staff upload task files" on storage.objects for insert to authenticated
with check (bucket_id = 'task-submissions' and private.current_app_role() in ('Owner', 'Wakil Owner', 'Kepala Divisi'));

revoke all on all functions in schema private from public;
grant usage on schema private to authenticated;
grant execute on all functions in schema private to authenticated;
grant execute on function public.mark_own_password_changed() to authenticated;
