create table if not exists app_users (
  id text primary key,
  name text not null,
  email text not null unique,
  role text not null check (role in ('Owner', 'Kepala Divisi', 'Staff', 'Magang', 'Wakil Owner', 'Developer', 'HRD')),
  division_id text not null default 'all',
  status text not null default 'Aktif',
  must_change_password boolean not null default true,
  password_set_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists password_events (
  id bigint generated by default as identity primary key,
  app_user_id text references app_users(id) on delete cascade,
  email text not null,
  event text not null check (event in ('temporary_created', 'temporary_reset', 'changed_by_user')),
  created_at timestamptz not null default now()
);

create table if not exists divisions (
  id text primary key,
  name text not null,
  head text,
  members integer not null default 0,
  description text,
  performance text
);

create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  position text,
  division_id text not null default 'all',
  role text not null,
  status text not null default 'Aktif',
  joined_at date
);

alter table app_users add column if not exists employee_id bigint references employees(id) on delete set null;

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  division_id text not null,
  assignee_id bigint,
  assigned_by text,
  assigned_by_name text,
  title text not null,
  description text,
  target text,
  priority text,
  deadline date,
  status text,
  approval text,
  progress integer not null default 0,
  note text,
  submission_note text,
  submission_file_url text,
  submission_file_name text,
  submitted_at timestamptz,
  approved_at timestamptz,
  approved_by text,
  history jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists task_email_notifications (
  id bigint generated by default as identity primary key,
  task_id bigint references tasks(id) on delete cascade,
  recipient_employee_id bigint references employees(id) on delete set null,
  recipient_name text not null,
  recipient_email text not null,
  subject text not null,
  message text not null,
  status text not null default 'Queued' check (status in ('Queued', 'Sent', 'Failed')),
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists task_submissions (
  id bigint generated by default as identity primary key,
  task_id bigint not null references tasks(id) on delete cascade,
  task_title text not null,
  task_description text,
  staff_name text not null,
  staff_role text not null,
  division_id text not null,
  deadline date,
  drive_link text not null,
  submission_note text,
  submitted_at timestamptz not null default now(),
  status text not null default 'Menunggu Review' check (status in ('Belum Dikumpulkan', 'Menunggu Review', 'Diterima', 'Revisi', 'Terlambat', 'Revisi Dikirim Ulang')),
  head_feedback text,
  reviewed_at timestamptz,
  reviewed_by text,
  reviewer_role text,
  revision_count integer not null default 0,
  revision_history jsonb not null default '[]'::jsonb,
  unique (task_id)
);

create table if not exists meetings (
  id bigint generated by default as identity primary key,
  date date,
  time text,
  division_id text not null default 'all',
  topic text not null,
  participants jsonb not null default '[]'::jsonb,
  status text
);

create table if not exists minutes (
  id bigint generated by default as identity primary key,
  title text not null,
  date date,
  time text,
  division_id text not null default 'all',
  leader text,
  participants jsonb not null default '[]'::jsonb,
  discussion text,
  decision text,
  follow_up text,
  action_deadline date
);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  employee_id bigint references employees(id) on delete set null,
  staff text not null,
  division_id text not null default 'all',
  done text,
  blockers text,
  next text,
  date date,
  status text
);

create table if not exists weekly_reports (
  id bigint generated by default as identity primary key,
  employee_id bigint references employees(id) on delete set null,
  week text not null,
  period text,
  staff text not null,
  division_id text not null default 'all',
  completed_tasks integer not null default 0,
  target_tasks integer not null default 0,
  average_progress integer not null default 0,
  late_tasks integer not null default 0,
  revision_tasks integer not null default 0,
  summary text,
  blocker text,
  next_plan text,
  head_note text,
  status text
);

create table if not exists announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  author text,
  date date,
  target text,
  priority text
);

create table if not exists documents (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  division_id text not null default 'all',
  uploaded_at date,
  type text,
  file_url text,
  file_name text,
  file_path text
);

create table if not exists app_settings (
  setting_key text primary key,
  setting_value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists activity_logs (
  id bigint generated by default as identity primary key,
  actor text,
  division_id text not null default 'all',
  action text not null,
  time text,
  severity text
);

create table if not exists sops (
  id bigint generated by default as identity primary key,
  title text not null,
  division_id text not null default 'all',
  description text,
  updated_at date,
  status text
);

alter table app_users enable row level security;
alter table divisions enable row level security;
alter table employees enable row level security;
alter table tasks enable row level security;
alter table task_email_notifications enable row level security;
alter table task_submissions enable row level security;
alter table meetings enable row level security;
alter table minutes enable row level security;
alter table reports enable row level security;
alter table weekly_reports enable row level security;
alter table announcements enable row level security;
alter table documents enable row level security;
alter table activity_logs enable row level security;
alter table sops enable row level security;
alter table app_settings enable row level security;

insert into storage.buckets (id, name, public)
values ('task-submissions', 'task-submissions', false)
on conflict (id) do update set public = false;

insert into storage.buckets (id, name, public)
values ('company-documents', 'company-documents', false)
on conflict (id) do update set public = false;

-- Policies intentionally fail closed here. Run supabase-role-policies.sql next.
