create table if not exists app_users (
  id text primary key,
  name text not null,
  email text not null unique,
  role text not null check (role in ('Owner', 'Kepala Divisi', 'Staff')),
  division_id text not null default 'all',
  status text not null default 'Aktif',
  created_at timestamptz not null default now()
);

create table if not exists divisions (
  id text primary key,
  name text not null,
  head text,
  members integer not null default 0,
  description text,
  performance text
);

create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  position text,
  division_id text not null default 'all',
  role text not null,
  status text not null default 'Aktif',
  joined_at date
);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  division_id text not null,
  assignee_id bigint,
  assigned_by text,
  assigned_by_name text,
  title text not null,
  description text,
  target text,
  priority text,
  deadline date,
  status text,
  approval text,
  progress integer not null default 0,
  note text,
  submission_note text,
  submission_file_url text,
  submission_file_name text,
  submitted_at timestamptz,
  approved_at timestamptz,
  approved_by text,
  history jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists meetings (
  id bigint generated by default as identity primary key,
  date date,
  time text,
  division_id text not null default 'all',
  topic text not null,
  participants jsonb not null default '[]'::jsonb,
  status text
);

create table if not exists minutes (
  id bigint generated by default as identity primary key,
  title text not null,
  date date,
  time text,
  division_id text not null default 'all',
  leader text,
  participants jsonb not null default '[]'::jsonb,
  discussion text,
  decision text,
  follow_up text,
  action_deadline date
);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  staff text not null,
  division_id text not null default 'all',
  done text,
  blockers text,
  next text,
  date date,
  status text
);

create table if not exists weekly_reports (
  id bigint generated by default as identity primary key,
  week text not null,
  period text,
  staff text not null,
  division_id text not null default 'all',
  completed_tasks integer not null default 0,
  target_tasks integer not null default 0,
  average_progress integer not null default 0,
  late_tasks integer not null default 0,
  revision_tasks integer not null default 0,
  summary text,
  blocker text,
  next_plan text,
  head_note text,
  status text
);

create table if not exists announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  author text,
  date date,
  target text,
  priority text
);

create table if not exists documents (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  division_id text not null default 'all',
  uploaded_at date,
  type text,
  file_url text,
  file_name text,
  file_path text
);

create table if not exists app_settings (
  setting_key text primary key,
  setting_value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists activity_logs (
  id bigint generated by default as identity primary key,
  actor text,
  division_id text not null default 'all',
  action text not null,
  time text,
  severity text
);

create table if not exists sops (
  id bigint generated by default as identity primary key,
  title text not null,
  division_id text not null default 'all',
  description text,
  updated_at date,
  status text
);

alter table app_users enable row level security;
alter table divisions enable row level security;
alter table employees enable row level security;
alter table tasks enable row level security;
alter table meetings enable row level security;
alter table minutes enable row level security;
alter table reports enable row level security;
alter table weekly_reports enable row level security;
alter table announcements enable row level security;
alter table documents enable row level security;
alter table activity_logs enable row level security;
alter table sops enable row level security;
alter table app_settings enable row level security;

create policy "authenticated read app_users" on app_users for select to authenticated using (true);
create policy "public read divisions" on divisions for select using (true);
create policy "public read employees" on employees for select using (true);
create policy "public read tasks" on tasks for select using (true);
create policy "public read meetings" on meetings for select using (true);
create policy "public read minutes" on minutes for select using (true);
create policy "public read reports" on reports for select using (true);
create policy "public read weekly_reports" on weekly_reports for select using (true);
create policy "public read announcements" on announcements for select using (true);
create policy "public read documents" on documents for select using (true);
create policy "public read activity_logs" on activity_logs for select using (true);
create policy "public read sops" on sops for select using (true);
create policy "public read app_settings" on app_settings for select using (true);

create policy "authenticated insert tasks" on tasks for insert to authenticated with check (true);
create policy "authenticated update tasks" on tasks for update to authenticated using (true) with check (true);
create policy "authenticated delete tasks" on tasks for delete to authenticated using (true);

create policy "authenticated insert activity_logs" on activity_logs for insert to authenticated with check (true);
create policy "authenticated update activity_logs" on activity_logs for update to authenticated using (true) with check (true);
create policy "authenticated delete activity_logs" on activity_logs for delete to authenticated using (true);

create policy "authenticated insert announcements" on announcements for insert to authenticated with check (true);
create policy "authenticated update announcements" on announcements for update to authenticated using (true) with check (true);
create policy "authenticated delete announcements" on announcements for delete to authenticated using (true);

create policy "authenticated insert reports" on reports for insert to authenticated with check (true);
create policy "authenticated update reports" on reports for update to authenticated using (true) with check (true);
create policy "authenticated delete reports" on reports for delete to authenticated using (true);

create policy "authenticated insert weekly_reports" on weekly_reports for insert to authenticated with check (true);
create policy "authenticated update weekly_reports" on weekly_reports for update to authenticated using (true) with check (true);
create policy "authenticated delete weekly_reports" on weekly_reports for delete to authenticated using (true);

create policy "authenticated update app_users" on app_users for update to authenticated using (true) with check (true);

create policy "authenticated insert documents" on documents for insert to authenticated with check (true);
create policy "authenticated update documents" on documents for update to authenticated using (true) with check (true);
create policy "authenticated delete documents" on documents for delete to authenticated using (true);

create policy "authenticated insert app_settings" on app_settings for insert to authenticated with check (true);
create policy "authenticated update app_settings" on app_settings for update to authenticated using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('task-submissions', 'task-submissions', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('company-documents', 'company-documents', true)
on conflict (id) do nothing;

create policy "authenticated upload task submissions"
on storage.objects for insert to authenticated
with check (bucket_id = 'task-submissions');

create policy "public read task submissions"
on storage.objects for select
using (bucket_id = 'task-submissions');

create policy "authenticated upload company documents"
on storage.objects for insert to authenticated
with check (bucket_id = 'company-documents');

create policy "public read company documents"
on storage.objects for select
using (bucket_id = 'company-documents');
